export const tableData = [
    { invoiceId: '01', name: 'Garry Morrison', email: 'curtis@example.com', address: 'Melbourne, Australia', deadline: '12-02-2024', details: 'View', status: true },
    { invoiceId: '02', name: 'Anderson John', email: 'jenn@example.com', address: 'New York, USA', deadline: '12-03-2024', details: 'View', status: false },
    { invoiceId: '03', name: 'Sunita Singh', email: 'sunita@example.com', address: 'India, Delhi', deadline: '12-03-2024', details: 'View', status: true },
    { invoiceId: '04', name: 'Kyle Janifer', email: 'Holt@example.com', address: 'London, UK', deadline: '12-03-2024', details: 'View', status: false },
    { invoiceId: '05', name: 'Ali Cheema', email: 'Ali@example.com', address: 'Lahore, Pakistan', deadline: '12-03-2024', details: 'View', status: true },
    { invoiceId: '06', name: 'Kyle Thomson', email: 'Rivera@example.com', address: 'Perth, Australia', deadline: '12-03-2024', details: 'View', status: false },
    { invoiceId: '07', name: 'Emma Stone', email: 'emma@example.com', address: 'Sydney, Australia', deadline: '12-04-2024', details: 'View', status: true },
    { invoiceId: '08', name: 'John Doe', email: 'john@example.com', address: 'Los Angeles, USA', deadline: '12-05-2024', details: 'View', status: false },
    { invoiceId: '09', name: 'Sophia Lee', email: 'sophia@example.com', address: 'Toronto, Canada', deadline: '12-06-2024', details: 'View', status: true },
    { invoiceId: '10', name: 'James Smith', email: 'james@example.com', address: 'Vancouver, Canada', deadline: '12-07-2024', details: 'View', status: false },
    { invoiceId: '11', name: 'Chris Green', email: 'chris@example.com', address: 'London, UK', deadline: '12-08-2024', details: 'View', status: true },
    { invoiceId: '12', name: 'Anna Belle', email: 'anna@example.com', address: 'Paris, France', deadline: '12-09-2024', details: 'View', status: false },
    { invoiceId: '13', name: 'Lucas Miller', email: 'lucas@example.com', address: 'Berlin, Germany', deadline: '12-10-2024', details: 'View', status: true },
    { invoiceId: '14', name: 'Natalie Brooks', email: 'natalie@example.com', address: 'Rome, Italy', deadline: '12-11-2024', details: 'View', status: false },
    { invoiceId: '15', name: 'Owen Carter', email: 'owen@example.com', address: 'Madrid, Spain', deadline: '12-12-2024', details: 'View', status: true },
    { invoiceId: '16', name: 'Zara Ahmed', email: 'zara@example.com', address: 'Dubai, UAE', deadline: '12-13-2024', details: 'View', status: false },
    { invoiceId: '17', name: 'Ella Johnson', email: 'ella@example.com', address: 'Copenhagen, Denmark', deadline: '12-14-2024', details: 'View', status: true },
    { invoiceId: '18', name: 'Jack Martin', email: 'jack@example.com', address: 'Amsterdam, Netherlands', deadline: '12-15-2024', details: 'View', status: false },
    { invoiceId: '19', name: 'Mia Clarke', email: 'mia@example.com', address: 'Brussels, Belgium', deadline: '12-16-2024', details: 'View', status: true },
    { invoiceId: '20', name: 'David Lee', email: 'david@example.com', address: 'Stockholm, Sweden', deadline: '12-17-2024', details: 'View', status: false },
    { invoiceId: '21', name: 'Eva Sanchez', email: 'eva@example.com', address: 'Lisbon, Portugal', deadline: '12-18-2024', details: 'View', status: true },
    { invoiceId: '22', name: 'Liam Scott', email: 'liam@example.com', address: 'Oslo, Norway', deadline: '12-19-2024', details: 'View', status: false },
    { invoiceId: '23', name: 'Ava Davis', email: 'ava@example.com', address: 'Vienna, Austria', deadline: '12-20-2024', details: 'View', status: true },
    { invoiceId: '24', name: 'Ethan Moore', email: 'ethan@example.com', address: 'Zurich, Switzerland', deadline: '12-21-2024', details: 'View', status: false },
    { invoiceId: '25', name: 'Charlotte Thomas', email: 'charlotte@example.com', address: 'Geneva, Switzerland', deadline: '12-22-2024', details: 'View', status: true },
    { invoiceId: '26', name: 'Mason White', email: 'mason@example.com', address: 'Vienna, Austria', deadline: '12-23-2024', details: 'View', status: false },
    { invoiceId: '27', name: 'Sophia Turner', email: 'sophia@example.com', address: 'Brussels, Belgium', deadline: '12-24-2024', details: 'View', status: true },
    { invoiceId: '28', name: 'James Wilson', email: 'james@example.com', address: 'Madrid, Spain', deadline: '12-25-2024', details: 'View', status: false },
    { invoiceId: '29', name: 'Amelia Moore', email: 'amelia@example.com', address: 'Paris, France', deadline: '12-26-2024', details: 'View', status: true },
    { invoiceId: '30', name: 'Liam Anderson', email: 'liam@example.com', address: 'Rome, Italy', deadline: '12-27-2024', details: 'View', status: false },
];
