const auctionData = [
    {
        id: 1,
        name: "Luxury Car Auction Mercedes Special Event",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "current",
        details: {
            location: "New York, USA",
            dateRange: "12-2-2024 to 12-3-2024",
            lotsAvailable: "12 Lots Available",
        },
    },
    {
        id: 2,
        name: "Classic Art Collection Exclusive Auction",
        image: `${process.env.PUBLIC_URL}/assets/pngs/watch.png`,
        type: "past",
        details: {
            location: "New York, USA",
            dateRange: "15-3-2024 to 17-3-2024",
            lotsAvailable: "8 Lots Available",
        },
    },
    {
        id: 3,
        name: "Real Estate Auction Prime Properties",
        image: `${process.env.PUBLIC_URL}/assets/pngs/jacket.png`,
        type: "current",
        details: {
            location: "New York, USA",
            dateRange: "20-4-2024 to 22-4-2024",
            lotsAvailable: "5 Lots Available",
        },
    },
    {
        id: 4,
        name: "Vintage Car Showcase Limited Edition Sale",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "past",
        details: {
            location: "New York, USA",
            dateRange: "10-5-2024 to 12-5-2024",
            lotsAvailable: "15 Lots Available",
        },
    },
    {
        id: 5,
        name: "Antique Jewelry Auction Rare Finds",
        image: `${process.env.PUBLIC_URL}/assets/pngs/watch.png`,
        type: "current",
        details: {
            location: "United Kingdom, London",
            dateRange: "18-6-2024 to 20-6-2024",
            lotsAvailable: "9 Lots Available",
        },
    },
    {
        id: 6,
        name: "Sports Memorabilia Sale Iconic Collectibles",
        image: `${process.env.PUBLIC_URL}/assets/pngs/jacket.png`,
        type: "past",
        details: {
            location: "United Kingdom, London",
            dateRange: "25-7-2024 to 27-7-2024",
            lotsAvailable: "20 Lots Available",
        },
    },
    {
        id: 7,
        name: "Modern Art Exhibition Curated Masterpieces",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "current",
        details: {
            location: "United Kingdom, London",
            dateRange: "5-8-2024 to 7-8-2024",
            lotsAvailable: "10 Lots Available",
        },
    },
    {
        id: 8,
        name: "Rare Book Auction Collector’s Edition",
        image: `${process.env.PUBLIC_URL}/assets/pngs/jacket.png`,
        type: "past",
        details: {
            location: "Pakistan, Islamabad",
            dateRange: "15-9-2024 to 17-9-2024",
            lotsAvailable: "7 Lots Available",
        },
    },
    {
        id: 9,
        name: "Collectible Coins Sale Limited Editions",
        image: `${process.env.PUBLIC_URL}/assets/pngs/watch.png`,
        type: "current",
        details: {
            location: "Pakistan, Islamabad",
            dateRange: "20-10-2024 to 22-10-2024",
            lotsAvailable: "13 Lots Available",
        },
    },
    {
        id: 10,
        name: "Tech Gadgets Auction Cutting-Edge Devices",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "current",
        details: {
            location: "Pakistan, Islamabad",
            dateRange: "1-11-2024 to 3-11-2024",
            lotsAvailable: "18 Lots Available",
        },
    },
    {
        id: 11,
        name: "Exclusive Wine Auction Rare Vintages",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "current",
        details: {
            location: "France, Paris",
            dateRange: "5-12-2024 to 7-12-2024",
            lotsAvailable: "25 Lots Available",
        },
    },
    {
        id: 12,
        name: "Luxury Watches Showcase Timeless Pieces",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "past",
        details: {
            location: "France, Paris",
            dateRange: "10-1-2024 to 12-1-2024",
            lotsAvailable: "30 Lots Available",
        },
    },
    {
        id: 13,
        name: "Antique Furniture Sale Classic Elegance",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "current",
        details: {
            location: "Germany, Berlin",
            dateRange: "15-2-2024 to 17-2-2024",
            lotsAvailable: "18 Lots Available",
        },
    },
    {
        id: 14,
        name: "Rare Stamps Auction Philatelic Treasures",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "past",
        details: {
            location: "Germany, Berlin",
            dateRange: "20-3-2024 to 22-3-2024",
            lotsAvailable: "22 Lots Available",
        },
    },
    {
        id: 15,
        name: "Classic Movie Memorabilia Auction",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "current",
        details: {
            location: "USA, Los Angeles",
            dateRange: "25-4-2024 to 27-4-2024",
            lotsAvailable: "14 Lots Available",
        },
    },
    {
        id: 16,
        name: "Luxury Yachts Auction Nautical Excellence",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "past",
        details: {
            location: "Italy, Venice",
            dateRange: "30-5-2024 to 1-6-2024",
            lotsAvailable: "5 Lots Available",
        },
    },
    {
        id: 17,
        name: "Jewelry Auction Exclusive Collections",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "current",
        details: {
            location: "India, Mumbai",
            dateRange: "10-7-2024 to 12-7-2024",
            lotsAvailable: "11 Lots Available",
        },
    },
    {
        id: 18,
        name: "Rare Comic Books Auction Collectible Editions",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "past",
        details: {
            location: "Japan, Tokyo",
            dateRange: "15-8-2024 to 17-8-2024",
            lotsAvailable: "19 Lots Available",
        },
    },
    {
        id: 19,
        name: "Vintage Cameras Sale Iconic Models",
        image: `${process.env.PUBLIC_URL}/assets/pngs/mercedes.png`,
        type: "current",
        details: {
            location: "UK, London",
            dateRange: "20-9-2024 to 22-9-2024",
            lotsAvailable: "8 Lots Available",
        },
    },
    {
        id: 20,
        name: "Luxury Home Auction Premium Estates",
        image: `${process.env.PUBLIC_URL}/assets/pngs/jacket.png`,
        type: "past",
        details: {
            location: "Canada, Toronto",
            dateRange: "25-10-2024 to 27-10-2024",
            lotsAvailable: "7 Lots Available",
        },
    },
    {
        id: 21,
        name: "Fine Art Auction Renaissance to Modern",
        image: `${process.env.PUBLIC_URL}/assets/pngs/jacket.png`,
        type: "current",
        details: {
            location: "Italy, Florence",
            dateRange: "1-11-2024 to 3-11-2024",
            lotsAvailable: "20 Lots Available",
        },
    },
    {
        id: 22,
        name: "Rare Vinyl Records Sale Iconic Albums",
        image: `${process.env.PUBLIC_URL}/assets/pngs/jacket.png`,
        type: "past",
        details: {
            location: "USA, Chicago",
            dateRange: "5-12-2024 to 7-12-2024",
            lotsAvailable: "10 Lots Available",
        },
    },
    {
        id: 23,
        name: "Exotic Cars Auction Supercars Collection",
        image: `${process.env.PUBLIC_URL}/assets/pngs/watch.png`,
        type: "current",
        details: {
            location: "UAE, Dubai",
            dateRange: "10-1-2025 to 12-1-2025",
            lotsAvailable: "6 Lots Available",
        },
    },
    {
        id: 24,
        name: "Classic Toys Auction Nostalgic Treasures",
        image: `${process.env.PUBLIC_URL}/assets/pngs/watch.png`,
        type: "past",
        details: {
            location: "Australia, Sydney",
            dateRange: "15-2-2025 to 17-2-2025",
            lotsAvailable: "12 Lots Available",
        },
    },
    {
        id: 25,
        name: "Rare Musical Instruments Auction",
        image: `${process.env.PUBLIC_URL}/assets/pngs/jacket.png`,
        type: "current",
        details: {
            location: "Brazil, Rio de Janeiro",
            dateRange: "20-3-2025 to 22-3-2025",
            lotsAvailable: "9 Lots Available",
        },
    },
    {
        id: 26,
        name: "Antique Clocks Auction Timeless Artifacts",
        image: `${process.env.PUBLIC_URL}/assets/pngs/jacket.png`,
        type: "past",
        details: {
            location: "Russia, Moscow",
            dateRange: "25-4-2025 to 27-4-2025",
            lotsAvailable: "15 Lots Available",
        },
    },
    {
        id: 27,
        name: "Vintage Posters Sale Graphic Masterpieces",
        image: `${process.env.PUBLIC_URL}/assets/pngs/jacket.png`,
        type: "current",
        details: {
            location: "South Africa, Cape Town",
            dateRange: "1-5-2025 to 3-5-2025",
            lotsAvailable: "14 Lots Available",
        },
    },
    {
        id: 28,
        name: "Exclusive Designer Handbags Auction",
        image: `${process.env.PUBLIC_URL}/assets/pngs/jacket.png`,
        type: "past",
        details: {
            location: "Spain, Madrid",
            dateRange: "5-6-2025 to 7-6-2025",
            lotsAvailable: "10 Lots Available",
        },
    },
    {
        id: 29,
        name: "Rare Coins Auction Ancient to Modern",
        image: `${process.env.PUBLIC_URL}/assets/pngs/jacket.png`,
        type: "current",
        details: {
            location: "India, Delhi",
            dateRange: "10-7-2025 to 12-7-2025",
            lotsAvailable: "16 Lots Available",
        },
    },
    {
        id: 30,
        name: "Antique Maps Sale Historic Cartography",
        image: `${process.env.PUBLIC_URL}/assets/pngs/jacket.png`,
        type: "past",
        details: {
            location: "Netherlands, Amsterdam",
            dateRange: "15-8-2025 to 17-8-2025",
            lotsAvailable: "7 Lots Available",
        },
    },
];

export default auctionData;
